# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"5\n\x10SummarizeRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"3\n\x11SummarizeResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"L\n\x16ProcessDocumentRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"J\n\x17ProcessDocumentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"0\n\x0b\x43hatRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\"-\n\x0c\x43hatResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"(\n\x15\x44ocumentStatusRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\"F\n\x16\x44ocumentStatusResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\x91\x02\n\nLLMService\x12:\n\tSummarize\x12\x15.llm.SummarizeRequest\x1a\x16.llm.SummarizeResponse\x12L\n\x0fProcessDocument\x12\x1b.llm.ProcessDocumentRequest\x1a\x1c.llm.ProcessDocumentResponse\x12+\n\x04\x43hat\x12\x10.llm.ChatRequest\x1a\x11.llm.ChatResponse\x12L\n\x11GetDocumentStatus\x12\x1a.llm.DocumentStatusRequest\x1a\x1b.llm.DocumentStatusResponseB\"Z backend/internal/llmclient/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z backend/internal/llmclient/proto'
  _globals['_SUMMARIZEREQUEST']._serialized_start=18
  _globals['_SUMMARIZEREQUEST']._serialized_end=71
  _globals['_SUMMARIZERESPONSE']._serialized_start=73
  _globals['_SUMMARIZERESPONSE']._serialized_end=124
  _globals['_PROCESSDOCUMENTREQUEST']._serialized_start=126
  _globals['_PROCESSDOCUMENTREQUEST']._serialized_end=202
  _globals['_PROCESSDOCUMENTRESPONSE']._serialized_start=204
  _globals['_PROCESSDOCUMENTRESPONSE']._serialized_end=278
  _globals['_CHATREQUEST']._serialized_start=280
  _globals['_CHATREQUEST']._serialized_end=328
  _globals['_CHATRESPONSE']._serialized_start=330
  _globals['_CHATRESPONSE']._serialized_end=375
  _globals['_DOCUMENTSTATUSREQUEST']._serialized_start=377
  _globals['_DOCUMENTSTATUSREQUEST']._serialized_end=417
  _globals['_DOCUMENTSTATUSRESPONSE']._serialized_start=419
  _globals['_DOCUMENTSTATUSRESPONSE']._serialized_end=489
  _globals['_LLMSERVICE']._serialized_start=492
  _globals['_LLMSERVICE']._serialized_end=765
# @@protoc_insertion_point(module_scope)
