# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """LLM service for document processing and Q&A
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Summarize = channel.unary_unary(
                '/llm.LLMService/Summarize',
                request_serializer=llm__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=llm__pb2.SummarizeResponse.FromString,
                _registered_method=True)
        self.ProcessDocument = channel.unary_unary(
                '/llm.LLMService/ProcessDocument',
                request_serializer=llm__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=llm__pb2.ProcessDocumentResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/llm.LLMService/Chat',
                request_serializer=llm__pb2.ChatRequest.SerializeToString,
                response_deserializer=llm__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GetDocumentStatus = channel.unary_unary(
                '/llm.LLMService/GetDocumentStatus',
                request_serializer=llm__pb2.DocumentStatusRequest.SerializeToString,
                response_deserializer=llm__pb2.DocumentStatusResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """LLM service for document processing and Q&A
    """

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=llm__pb2.SummarizeRequest.FromString,
                    response_serializer=llm__pb2.SummarizeResponse.SerializeToString,
            ),
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=llm__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=llm__pb2.ProcessDocumentResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=llm__pb2.ChatRequest.FromString,
                    response_serializer=llm__pb2.ChatResponse.SerializeToString,
            ),
            'GetDocumentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentStatus,
                    request_deserializer=llm__pb2.DocumentStatusRequest.FromString,
                    response_serializer=llm__pb2.DocumentStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """LLM service for document processing and Q&A
    """

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/Summarize',
            llm__pb2.SummarizeRequest.SerializeToString,
            llm__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/ProcessDocument',
            llm__pb2.ProcessDocumentRequest.SerializeToString,
            llm__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/Chat',
            llm__pb2.ChatRequest.SerializeToString,
            llm__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/GetDocumentStatus',
            llm__pb2.DocumentStatusRequest.SerializeToString,
            llm__pb2.DocumentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
